"""test

Revision ID: 279aa5d9a967
Revises: 
Create Date: 2020-05-26 09:20:53.851786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279aa5d9a967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppy',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppy')
    # ### end Alembic commands ###
